name: discordcore
version: '${project.version}'
main: austxnsheep.main.Main
api-version: 1.19

commands:
  std:
    description: Sends message to discord
    usage: /std
    permission: discordcore.std
  stdw:
    description: Sends message to discord without a profile picture
    usage: /stdw
    permission: discordcore.stdw
  discord:
    description: Sends a link to our discord
    usage /discord
    permission: discordcore.discord